version: '3.8'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./:/opt/app:cached
      - /opt/app/node_modules
    command: npm run develop

  strapiDB:
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d:ro
      - ./scripts:/scripts:ro
